#define CODE_ANALYSIS

using System.Diagnostics.CodeAnalysis;

// C# top-level statements intentionally place the generated Program type in the
// anonymous namespace.
[assembly: SuppressMessage("NDepend", "ND1307", Target = "ApiBureau.Bullhorn.Api.Console:{anonymous namespace}", Justification = "The console entry point uses C# top-level statements.")]
[assembly: SuppressMessage("NDepend", "ND1307", Target = "ApiBureau.Bullhorn.Browser:{anonymous namespace}", Justification = "The web entry point uses C# top-level statements.")]
[assembly: SuppressMessage("NDepend", "ND1307", Target = "ApiBureau.Devyce.Api.Console:{anonymous namespace}", Justification = "The console entry point uses C# top-level statements.")]
[assembly: SuppressMessage("NDepend", "ND1307", Target = "ApiBureau.JPMorgan.Api.Console:{anonymous namespace}", Justification = "The console entry point uses C# top-level statements.")]
[assembly: SuppressMessage("NDepend", "ND1307", Target = "ApiBureau.Ringover.Api.Console:{anonymous namespace}", Justification = "The console entry point uses C# top-level statements.")]
[assembly: SuppressMessage("NDepend", "ND1307", Target = "{anonymous namespace}", Justification = "The console entry point uses C# top-level statements.")]

// Private static fields follow the same underscore-prefixed convention as other
// private fields in these projects.
[assembly: SuppressMessage("NDepend", "ND2001", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Helpers.DateColumnChecker._predefinedColumns", Justification = "The field follows the repository convention for private fields.")]
[assembly: SuppressMessage("NDepend", "ND2001", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Helpers.JsonHelper._cachedOptions", Justification = "The field follows the repository convention for private fields.")]
[assembly: SuppressMessage("NDepend", "ND2001", Target = "ApiBureau.JPMorgan.Api:ApiBureau.JPMorgan.Api.Http.ApiConnection._jsonOptions", Justification = "The field follows the repository convention for private fields.")]

// These small companion models intentionally live beside the primary model they
// support. Splitting them would add navigation overhead without changing design.
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Http.ErrorResponse", Justification = "Closely related response models are intentionally colocated.")]
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Http.OAuthRequestBase", Justification = "Closely related OAuth models are intentionally colocated.")]
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Http.SearchResponse", Justification = "Closely related response models are intentionally colocated.")]
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Dtos.AppointmentDto", Justification = "Closely related DTOs are intentionally colocated.")]
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Dtos.DepartmentsDto", Justification = "Closely related DTOs are intentionally colocated.")]
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.Ringover.Api:ApiBureau.Ringover.Api.Dtos.TranscriptionDto", Justification = "Closely related transcription DTOs are intentionally colocated.")]
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.JPMorgan.Api:ApiBureau.JPMorgan.Api.Http.OAuthClientExtensions", Justification = "The private OAuth helper is intentionally colocated with its extension entry point.")]

// Devyce endpoint paths are relative HTTP request targets combined with the
// configured HttpClient.BaseAddress, not standalone absolute URI values.
[assembly: SuppressMessage("NDepend", "ND2209", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.ContactEndpoint.BaseUrl", Justification = "The value is a relative endpoint path.")]
[assembly: SuppressMessage("NDepend", "ND2209", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.CrmSyncDetailsEndpoint.BaseUrl", Justification = "The value is a relative endpoint path.")]
[assembly: SuppressMessage("NDepend", "ND2209", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.TranscriptEndpoint.BaseUrl", Justification = "The value is a relative endpoint path.")]
[assembly: SuppressMessage("NDepend", "ND2209", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.UserEndpoint.BaseUrl", Justification = "The value is a relative endpoint path.")]

// EqualityContract is generated by the compiler for records and has no editable
// source declaration of its own.
[assembly: SuppressMessage("NDepend", "ND1208", Scope = "method", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Queries.CallQuery", Justification = "The reported EqualityContract getter is compiler-generated record infrastructure.")]
[assembly: SuppressMessage("NDepend", "ND1208", Scope = "method", Target = "ApiBureau.Ringover.Api:ApiBureau.Ringover.Api.Queries.CallQuery", Justification = "The reported EqualityContract getter is compiler-generated record infrastructure.")]
[assembly: SuppressMessage("NDepend", "ND1208", Scope = "method", Target = "ApiBureau.Ringover.Api:ApiBureau.Ringover.Api.Queries.TranscriptQuery", Justification = "The reported EqualityContract getter is compiler-generated record infrastructure.")]

[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "ApiBureau.Bullhorn.Browser:ApiBureau.Bullhorn.Browser.Pages.Index.GetData()", Justification = "TODO")]