#define CODE_ANALYSIS

using System.Diagnostics.CodeAnalysis;

// C# top-level statements intentionally place the generated Program type in the
// anonymous namespace.
[assembly: SuppressMessage("NDepend", "ND1307", Target = "ApiBureau.Bullhorn.Api.Console:{anonymous namespace}", Justification = "The console entry point uses C# top-level statements.")]
[assembly: SuppressMessage("NDepend", "ND1307", Target = "ApiBureau.Bullhorn.Browser:{anonymous namespace}", Justification = "The web entry point uses C# top-level statements.")]
[assembly: SuppressMessage("NDepend", "ND1307", Target = "ApiBureau.Devyce.Api.Console:{anonymous namespace}", Justification = "The console entry point uses C# top-level statements.")]
[assembly: SuppressMessage("NDepend", "ND1307", Target = "ApiBureau.JPMorgan.Api.Console:{anonymous namespace}", Justification = "The console entry point uses C# top-level statements.")]
[assembly: SuppressMessage("NDepend", "ND1307", Target = "ApiBureau.Ringover.Api.Console:{anonymous namespace}", Justification = "The console entry point uses C# top-level statements.")]
[assembly: SuppressMessage("NDepend", "ND1307", Target = "{anonymous namespace}", Justification = "The console entry point uses C# top-level statements.")]

// Private static fields follow the same underscore-prefixed convention as other
// private fields in these projects.
[assembly: SuppressMessage("NDepend", "ND2001", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Helpers.DateColumnChecker._predefinedColumns", Justification = "The field follows the repository convention for private fields.")]
[assembly: SuppressMessage("NDepend", "ND2001", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Helpers.JsonHelper._cachedOptions", Justification = "The field follows the repository convention for private fields.")]
[assembly: SuppressMessage("NDepend", "ND2001", Target = "ApiBureau.JPMorgan.Api:ApiBureau.JPMorgan.Api.Http.ApiConnection._jsonOptions", Justification = "The field follows the repository convention for private fields.")]

// These small companion models intentionally live beside the primary model they
// support. Splitting them would add navigation overhead without changing design.
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Http.ErrorResponse", Justification = "Closely related response models are intentionally colocated.")]
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Http.OAuthRequestBase", Justification = "Closely related OAuth models are intentionally colocated.")]
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Http.SearchResponse", Justification = "Closely related response models are intentionally colocated.")]
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Dtos.AppointmentDto", Justification = "Closely related DTOs are intentionally colocated.")]
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Dtos.DepartmentsDto", Justification = "Closely related DTOs are intentionally colocated.")]
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.Ringover.Api:ApiBureau.Ringover.Api.Dtos.TranscriptionDto", Justification = "Closely related transcription DTOs are intentionally colocated.")]
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.JPMorgan.Api:ApiBureau.JPMorgan.Api.Http.OAuthClientExtensions", Justification = "The private OAuth helper is intentionally colocated with its extension entry point.")]

// Devyce endpoint paths are relative HTTP request targets combined with the
// configured HttpClient.BaseAddress, not standalone absolute URI values.
[assembly: SuppressMessage("NDepend", "ND2209", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.ContactEndpoint.BaseUrl", Justification = "The value is a relative endpoint path.")]
[assembly: SuppressMessage("NDepend", "ND2209", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.CrmSyncDetailsEndpoint.BaseUrl", Justification = "The value is a relative endpoint path.")]
[assembly: SuppressMessage("NDepend", "ND2209", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.TranscriptEndpoint.BaseUrl", Justification = "The value is a relative endpoint path.")]
[assembly: SuppressMessage("NDepend", "ND2209", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.UserEndpoint.BaseUrl", Justification = "The value is a relative endpoint path.")]

// EqualityContract is generated by the compiler for records and has no editable
// source declaration of its own.
[assembly: SuppressMessage("NDepend", "ND1208", Scope = "method", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Queries.CallQuery", Justification = "The reported EqualityContract getter is compiler-generated record infrastructure.")]
[assembly: SuppressMessage("NDepend", "ND1208", Scope = "method", Target = "ApiBureau.Ringover.Api:ApiBureau.Ringover.Api.Queries.CallQuery", Justification = "The reported EqualityContract getter is compiler-generated record infrastructure.")]
[assembly: SuppressMessage("NDepend", "ND1208", Scope = "method", Target = "ApiBureau.Ringover.Api:ApiBureau.Ringover.Api.Queries.TranscriptQuery", Justification = "The reported EqualityContract getter is compiler-generated record infrastructure.")]

// IBullhornClient is intentionally a cohesive facade over the available endpoint
// groups. Splitting it would fragment and break the public client contract.
[assembly: SuppressMessage("NDepend", "ND1200", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Interfaces.IBullhornClient", Justification = "The interface is the public endpoint facade for the Bullhorn client.")]

// DataId reflects the nested data item in the EntityChildren wire contract.
// Extracting it would break the existing public DTO type name.
[assembly: SuppressMessage("NDepend", "ND1306", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Dtos.EntityChildrenDto+DataId", Justification = "The nested public type is part of the established wire-model API.")]

// Top-level statements generate an anonymous Program namespace. Its generated
// state machine creates an analysis-only cycle with the console service namespace.
[assembly: SuppressMessage("NDepend", "ND1400", Target = "ApiBureau.Devyce.Api.Console:Program+<<Main>$>d__0", Justification = "The dependency is generated by the top-level console entry point.")]
[assembly: SuppressMessage("NDepend", "ND1401", Target = "ApiBureau.Devyce.Api.Console:{anonymous namespace}", Justification = "The cycle includes the generated top-level Program namespace.")]

// The public Bullhorn facade necessarily connects the root, Interfaces, and
// Endpoints namespaces. Moving the established public types would break consumers.
[assembly: SuppressMessage("NDepend", "ND1400", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Interfaces.IBullhornClient", Justification = "The dependency is intrinsic to the established public client facade.")]
[assembly: SuppressMessage("NDepend", "ND1401", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api", Justification = "Breaking the public namespace cycle would require moving established API types.")]

// These namespaces intentionally group many independent endpoint and transport
// models. Low relational cohesion is expected and is not an actionable defect.
[assembly: SuppressMessage("NDepend", "ND1406", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints", Justification = "Endpoint types are independent entry points grouped by API concern.")]
[assembly: SuppressMessage("NDepend", "ND1406", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Http", Justification = "HTTP transport and response types are intentionally grouped by infrastructure concern.")]

// ApiSession remains a separate internal type to keep authentication/session logic
// isolated and independently maintainable rather than nesting it in the HTTP client.
[assembly: SuppressMessage("NDepend", "ND1803", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Http.ApiSession", Justification = "A separate type preserves session encapsulation and testability.")]

[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "ApiBureau.Bullhorn.Browser:ApiBureau.Bullhorn.Browser.Pages.Index.GetData()", Justification = "TODO")]