#define CODE_ANALYSIS

using System.Diagnostics.CodeAnalysis;

// C# top-level statements intentionally place the generated Program type in the
// anonymous namespace.
[assembly: SuppressMessage("NDepend", "ND1307", Target = "ApiBureau.Bullhorn.Api.Console:{anonymous namespace}", Justification = "The console entry point uses C# top-level statements.")]
[assembly: SuppressMessage("NDepend", "ND1307", Target = "ApiBureau.Bullhorn.Browser:{anonymous namespace}", Justification = "The web entry point uses C# top-level statements.")]
[assembly: SuppressMessage("NDepend", "ND1307", Target = "ApiBureau.Devyce.Api.Console:{anonymous namespace}", Justification = "The console entry point uses C# top-level statements.")]
[assembly: SuppressMessage("NDepend", "ND1307", Target = "ApiBureau.JPMorgan.Api.Console:{anonymous namespace}", Justification = "The console entry point uses C# top-level statements.")]
[assembly: SuppressMessage("NDepend", "ND1307", Target = "ApiBureau.Ringover.Api.Console:{anonymous namespace}", Justification = "The console entry point uses C# top-level statements.")]
[assembly: SuppressMessage("NDepend", "ND1307", Target = "{anonymous namespace}", Justification = "The console entry point uses C# top-level statements.")]

// Private static fields follow the same underscore-prefixed convention as other
// private fields in these projects.
[assembly: SuppressMessage("NDepend", "ND2001", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Helpers.DateColumnChecker._predefinedColumns", Justification = "The field follows the repository convention for private fields.")]
[assembly: SuppressMessage("NDepend", "ND2001", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Helpers.JsonHelper._cachedOptions", Justification = "The field follows the repository convention for private fields.")]
[assembly: SuppressMessage("NDepend", "ND2001", Target = "ApiBureau.JPMorgan.Api:ApiBureau.JPMorgan.Api.Http.ApiConnection._jsonOptions", Justification = "The field follows the repository convention for private fields.")]

// These small companion models intentionally live beside the primary model they
// support. Splitting them would add navigation overhead without changing design.
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Http.ErrorResponse", Justification = "Closely related response models are intentionally colocated.")]
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Http.OAuthRequestBase", Justification = "Closely related OAuth models are intentionally colocated.")]
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Http.SearchResponse", Justification = "Closely related response models are intentionally colocated.")]
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Dtos.AppointmentDto", Justification = "Closely related DTOs are intentionally colocated.")]
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Dtos.DepartmentsDto", Justification = "Closely related DTOs are intentionally colocated.")]
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.Ringover.Api:ApiBureau.Ringover.Api.Dtos.TranscriptionDto", Justification = "Closely related transcription DTOs are intentionally colocated.")]
[assembly: SuppressMessage("NDepend", "ND2102", Target = "ApiBureau.JPMorgan.Api:ApiBureau.JPMorgan.Api.Http.OAuthClientExtensions", Justification = "The private OAuth helper is intentionally colocated with its extension entry point.")]

// Devyce endpoint paths are relative HTTP request targets combined with the
// configured HttpClient.BaseAddress, not standalone absolute URI values.
[assembly: SuppressMessage("NDepend", "ND2209", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.ContactEndpoint.BaseUrl", Justification = "The value is a relative endpoint path.")]
[assembly: SuppressMessage("NDepend", "ND2209", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.CrmSyncDetailsEndpoint.BaseUrl", Justification = "The value is a relative endpoint path.")]
[assembly: SuppressMessage("NDepend", "ND2209", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.TranscriptEndpoint.BaseUrl", Justification = "The value is a relative endpoint path.")]
[assembly: SuppressMessage("NDepend", "ND2209", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.UserEndpoint.BaseUrl", Justification = "The value is a relative endpoint path.")]

// EqualityContract is generated by the compiler for records and has no editable
// source declaration of its own.
[assembly: SuppressMessage("NDepend", "ND1208", Scope = "method", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Queries.CallQuery", Justification = "The reported EqualityContract getter is compiler-generated record infrastructure.")]
[assembly: SuppressMessage("NDepend", "ND1208", Scope = "method", Target = "ApiBureau.Ringover.Api:ApiBureau.Ringover.Api.Queries.CallQuery", Justification = "The reported EqualityContract getter is compiler-generated record infrastructure.")]
[assembly: SuppressMessage("NDepend", "ND1208", Scope = "method", Target = "ApiBureau.Ringover.Api:ApiBureau.Ringover.Api.Queries.TranscriptQuery", Justification = "The reported EqualityContract getter is compiler-generated record infrastructure.")]

// IBullhornClient is intentionally a cohesive facade over the available endpoint
// groups. Splitting it would fragment and break the public client contract.
[assembly: SuppressMessage("NDepend", "ND1200", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Interfaces.IBullhornClient", Justification = "The interface is the public endpoint facade for the Bullhorn client.")]

// DataId reflects the nested data item in the EntityChildren wire contract.
// Extracting it would break the existing public DTO type name.
[assembly: SuppressMessage("NDepend", "ND1306", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Dtos.EntityChildrenDto+DataId", Justification = "The nested public type is part of the established wire-model API.")]

// Top-level statements generate an anonymous Program namespace. Its generated
// state machine creates an analysis-only cycle with the console service namespace.
[assembly: SuppressMessage("NDepend", "ND1400", Target = "ApiBureau.Devyce.Api.Console:Program+<<Main>$>d__0", Justification = "The dependency is generated by the top-level console entry point.")]
[assembly: SuppressMessage("NDepend", "ND1401", Target = "ApiBureau.Devyce.Api.Console:{anonymous namespace}", Justification = "The cycle includes the generated top-level Program namespace.")]

// The public Bullhorn facade necessarily connects the root, Interfaces, and
// Endpoints namespaces. Moving the established public types would break consumers.
[assembly: SuppressMessage("NDepend", "ND1400", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Interfaces.IBullhornClient", Justification = "The dependency is intrinsic to the established public client facade.")]
[assembly: SuppressMessage("NDepend", "ND1401", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api", Justification = "Breaking the public namespace cycle would require moving established API types.")]

// These namespaces intentionally group many independent endpoint and transport
// models. Low relational cohesion is expected and is not an actionable defect.
[assembly: SuppressMessage("NDepend", "ND1406", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints", Justification = "Endpoint types are independent entry points grouped by API concern.")]
[assembly: SuppressMessage("NDepend", "ND1406", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Http", Justification = "HTTP transport and response types are intentionally grouped by infrastructure concern.")]

// ApiSession remains a separate internal type to keep authentication/session logic
// isolated and independently maintainable rather than nesting it in the HTTP client.
[assembly: SuppressMessage("NDepend", "ND1803", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Http.ApiSession", Justification = "A separate type preserves session encapsulation and testability.")]

// isDeleted is an established mutable request-contract field. Replacing it with
// a property or making it readonly would be a binary/source compatibility break.
[assembly: SuppressMessage("NDepend", "ND1805", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Dtos.SoftDeleteDto.isDeleted", Justification = "The field is part of the established mutable request DTO contract.")]

// RunAsync is a straightforward command dispatcher whose branches are already
// described by command names and the generated help output.
[assembly: SuppressMessage("NDepend", "ND1006", Scope = "method", Target = "ApiBureau.Confluence.Api.Console:ApiBureau.Confluence.Api.Console.Services.ConfluenceConsoleService", Justification = "Additional implementation comments would duplicate the self-describing command dispatch and help text.")]

// These API changes belong to the previously reviewed Bullhorn transport and
// endpoint-facade redesign. Compatibility shims would expose obsolete transport
// details and duplicate every renamed endpoint member indefinitely.
[assembly: SuppressMessage("NDepend", "ND1500", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Http.ApiSession", Justification = "Session management is intentionally an internal transport detail.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.BullhornClient", Justification = "The client API was intentionally redesigned around endpoint groups and an advanced client.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Interfaces.IBullhornClient", Justification = "The client interface intentionally uses plural endpoint group names.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.AppointmentEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.CandidateEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.CandidateWorkHistoryEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.ClientContactEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.ClientCorporationEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.CorporateUserEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.CorporationDepartmentEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.CountryEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.DepartmentEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.EntityEditHistoryEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.EventEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.FileAttachmentEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.FileEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.JobOrderEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.JobSubmissionEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.JobSubmissionHistoryEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.MassUpdateEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.NoteEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.OpportunityEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.PlacementChangeRequestEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.PlacementCommissionEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.PlacementEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.QueryEndpointBase<T>", Justification = "The endpoint base API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.ResumeEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.SearchEndpointBase<T>", Justification = "The endpoint base API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Endpoints.SendoutEndpoint", Justification = "The endpoint API was intentionally redesigned.")]
[assembly: SuppressMessage("NDepend", "ND1503", Target = "ApiBureau.Bullhorn.Api:ApiBureau.Bullhorn.Api.Interfaces.IBullhornClient", Justification = "The singular endpoint properties and raw query methods were intentionally replaced by plural groups and Advanced.")]

// Devyce endpoints are created by DevyceClient so consumers always receive the
// configured shared HTTP client. Public constructors would permit invalid clients.
[assembly: SuppressMessage("NDepend", "ND1501", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.CallEndpoint", Justification = "Endpoint construction is intentionally controlled by DevyceClient.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.CallEndpoint", Justification = "The constructor is internal to enforce configured client creation.")]
[assembly: SuppressMessage("NDepend", "ND1501", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.ContactEndpoint", Justification = "Endpoint construction is intentionally controlled by DevyceClient.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.ContactEndpoint", Justification = "The constructor is internal to enforce configured client creation.")]
[assembly: SuppressMessage("NDepend", "ND1501", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.CrmSyncDetailsEndpoint", Justification = "Endpoint construction is intentionally controlled by DevyceClient.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.CrmSyncDetailsEndpoint", Justification = "The constructor is internal to enforce configured client creation.")]
[assembly: SuppressMessage("NDepend", "ND1501", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.TranscriptEndpoint", Justification = "Endpoint construction is intentionally controlled by DevyceClient.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.TranscriptEndpoint", Justification = "The constructor is internal to enforce configured client creation.")]
[assembly: SuppressMessage("NDepend", "ND1501", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.UserEndpoint", Justification = "Endpoint construction is intentionally controlled by DevyceClient.")]
[assembly: SuppressMessage("NDepend", "ND1501", Scope = "method", Target = "ApiBureau.Devyce.Api:ApiBureau.Devyce.Api.Endpoints.UserEndpoint", Justification = "The constructor is internal to enforce configured client creation.")]

[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "ApiBureau.Bullhorn.Browser:ApiBureau.Bullhorn.Browser.Pages.Index.GetData()", Justification = "TODO")]
